name: Deploy Frontend Vidal Casino to AWS EKS

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Autenticarse en AWS con los Repository Secrets de AWS Academy
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # 2. Loguearse de forma automática a Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Compilar la imagen Docker y subirla a tu repositorio de AWS ECR
      - name: Build and Push Docker Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: vidalcasino-frontend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-eks:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Autenticarse de nuevo en AWS para interactuar con el clúster
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # 2. Conectar GitHub Actions al clúster de EKS
      - name: Update Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name vidal-casino-cluster

      # 3. Ordenar a Kubernetes que refresque el despliegue con la nueva imagen
      - name: Deploy Manifests to EKS
        run: |
          # Esto fuerza a Kubernetes a reiniciar los pods con la nueva imagen subida a ECR
          kubectl rollout restart deployment/vidalcasino-frontend-deployment || true